server:
  port: 9090
  servlet:
    context-path: /v1

spring:
  application:
    name: springboot-thread

  # 数据库的配置
  # allowMultiQueries=true 允许批量更新和插入
  # &rewriteBatchedStatements=true 允许数据批量提交
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.0.27:3306/datatestui?allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 20
      max-active: 200

      # 配置获取连接等待超时的时间
      max-wait: 60000

      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000

      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 打开PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # 配置监控统计拦截的 filters，去掉后监控界面sql无法统计，'stat'监控慢SQL功能，'wall'用于防火墙，‘slf4j’指定日志组件，将操作写入到日志中
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      filters: stat,wall,slf4j
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 配置内置界面地址，用户名和密码，慎用，会存在信息泄露的风险
      # 内置地址：http://ip:post/druid/index.html
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow:
        login-username: root
        login-password: 123456

 # 多线程配置
  task:
    execution:
      pool:
        core-size: 10
        max-size: 200
        queue-capacity: 400
        keep-alive: 60
      thread-name-prefix: thread-

  # 允许上传文件大小配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

