server:
  port: 9091

spring:
  application:
    name: springboot-redis

  redis:
    # Redis服务器地址
    host: 122.112.166.49
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 1
    password: Galaxyeye01
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 1000
