server:
  port: 9091

spring:
  application:
    name: springboot-nacos-provide

  cloud:
    loadbalancer:
      retry:
        enabled: true
      enabled: true

    nacos:
      discovery:
        server-addr: 172.16.0.127:8848
